/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAlunosRouteImport } from './routes/admin/alunos'
import { Route as AdminAuditoriaRouteImport } from './routes/admin/auditoria'
import { Route as AdminConteudosRouteImport } from './routes/admin/conteudos'
import { Route as AdminPerfilRouteImport } from './routes/admin/perfil'
import { Route as AdminRequerimentosSenhaRouteImport } from './routes/admin/requerimentos-senha'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCronicasRouteImport } from './routes/app/cronicas'
import { Route as AppLivrosRouteImport } from './routes/app/livros'
import { Route as AppMusicasRouteImport } from './routes/app/musicas'
import { Route as AppPerfilRouteImport } from './routes/app/perfil'
import { Route as AppPoemasRouteImport } from './routes/app/poemas'
import { Route as AdminConteudosConteudoIdRouteImport } from './routes/admin/conteudos.$conteudoId'
import { Route as AppConteudosConteudoIdRouteImport } from './routes/app/conteudos.$conteudoId'
import { Route as AppPerfilSenhaRouteImport } from './routes/app/perfil.senha'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAlunosRoute = AdminAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConteudosRoute = AdminConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPerfilRoute = AdminPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRequerimentosSenhaRoute = AdminRequerimentosSenhaRouteImport.update({
  id: '/requerimentos-senha',
  path: '/requerimentos-senha',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCronicasRoute = AppCronicasRouteImport.update({
  id: '/cronicas',
  path: '/cronicas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLivrosRoute = AppLivrosRouteImport.update({
  id: '/livros',
  path: '/livros',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMusicasRoute = AppMusicasRouteImport.update({
  id: '/musicas',
  path: '/musicas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPoemasRoute = AppPoemasRouteImport.update({
  id: '/poemas',
  path: '/poemas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminConteudosConteudoIdRoute =
  AdminConteudosConteudoIdRouteImport.update({
    id: '/$conteudoId',
    path: '/$conteudoId',
    getParentRoute: () => AdminConteudosRoute,
  } as any)
const AppConteudosConteudoIdRoute = AppConteudosConteudoIdRouteImport.update({
  id: '/conteudos/$conteudoId',
  path: '/conteudos/$conteudoId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPerfilSenhaRoute = AppPerfilSenhaRouteImport.update({
  id: '/senha',
  path: '/senha',
  getParentRoute: () => AppPerfilRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/conteudos': typeof AdminConteudosRouteWithChildren
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/requerimentos-senha': typeof AdminRequerimentosSenhaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/cronicas': typeof AppCronicasRoute
  '/app/livros': typeof AppLivrosRoute
  '/app/musicas': typeof AppMusicasRoute
  '/app/perfil': typeof AppPerfilRouteWithChildren
  '/app/poemas': typeof AppPoemasRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/conteudos/$conteudoId': typeof AdminConteudosConteudoIdRoute
  '/app/conteudos/$conteudoId': typeof AppConteudosConteudoIdRoute
  '/app/perfil/senha': typeof AppPerfilSenhaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/conteudos': typeof AdminConteudosRouteWithChildren
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/requerimentos-senha': typeof AdminRequerimentosSenhaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/cronicas': typeof AppCronicasRoute
  '/app/livros': typeof AppLivrosRoute
  '/app/musicas': typeof AppMusicasRoute
  '/app/perfil': typeof AppPerfilRouteWithChildren
  '/app/poemas': typeof AppPoemasRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/conteudos/$conteudoId': typeof AdminConteudosConteudoIdRoute
  '/app/conteudos/$conteudoId': typeof AppConteudosConteudoIdRoute
  '/app/perfil/senha': typeof AppPerfilSenhaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/conteudos': typeof AdminConteudosRouteWithChildren
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/requerimentos-senha': typeof AdminRequerimentosSenhaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/cronicas': typeof AppCronicasRoute
  '/app/livros': typeof AppLivrosRoute
  '/app/musicas': typeof AppMusicasRoute
  '/app/perfil': typeof AppPerfilRouteWithChildren
  '/app/poemas': typeof AppPoemasRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/conteudos/$conteudoId': typeof AdminConteudosConteudoIdRoute
  '/app/conteudos/$conteudoId': typeof AppConteudosConteudoIdRoute
  '/app/perfil/senha': typeof AppPerfilSenhaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/esqueci-senha'
    | '/login'
    | '/redefinir-senha'
    | '/admin/alunos'
    | '/admin/auditoria'
    | '/admin/conteudos'
    | '/admin/perfil'
    | '/admin/requerimentos-senha'
    | '/admin/usuarios'
    | '/app/cronicas'
    | '/app/livros'
    | '/app/musicas'
    | '/app/perfil'
    | '/app/poemas'
    | '/admin/'
    | '/app/'
    | '/admin/conteudos/$conteudoId'
    | '/app/conteudos/$conteudoId'
    | '/app/perfil/senha'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/esqueci-senha'
    | '/login'
    | '/redefinir-senha'
    | '/admin/alunos'
    | '/admin/auditoria'
    | '/admin/conteudos'
    | '/admin/perfil'
    | '/admin/requerimentos-senha'
    | '/admin/usuarios'
    | '/app/cronicas'
    | '/app/livros'
    | '/app/musicas'
    | '/app/perfil'
    | '/app/poemas'
    | '/admin'
    | '/app'
    | '/admin/conteudos/$conteudoId'
    | '/app/conteudos/$conteudoId'
    | '/app/perfil/senha'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/esqueci-senha'
    | '/login'
    | '/redefinir-senha'
    | '/admin/alunos'
    | '/admin/auditoria'
    | '/admin/conteudos'
    | '/admin/perfil'
    | '/admin/requerimentos-senha'
    | '/admin/usuarios'
    | '/app/cronicas'
    | '/app/livros'
    | '/app/musicas'
    | '/app/perfil'
    | '/app/poemas'
    | '/admin/'
    | '/app/'
    | '/admin/conteudos/$conteudoId'
    | '/app/conteudos/$conteudoId'
    | '/app/perfil/senha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/alunos': {
      id: '/admin/alunos'
      path: '/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AdminAlunosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/conteudos': {
      id: '/admin/conteudos'
      path: '/conteudos'
      fullPath: '/admin/conteudos'
      preLoaderRoute: typeof AdminConteudosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/perfil': {
      id: '/admin/perfil'
      path: '/perfil'
      fullPath: '/admin/perfil'
      preLoaderRoute: typeof AdminPerfilRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/requerimentos-senha': {
      id: '/admin/requerimentos-senha'
      path: '/requerimentos-senha'
      fullPath: '/admin/requerimentos-senha'
      preLoaderRoute: typeof AdminRequerimentosSenhaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/cronicas': {
      id: '/app/cronicas'
      path: '/cronicas'
      fullPath: '/app/cronicas'
      preLoaderRoute: typeof AppCronicasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/livros': {
      id: '/app/livros'
      path: '/livros'
      fullPath: '/app/livros'
      preLoaderRoute: typeof AppLivrosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/musicas': {
      id: '/app/musicas'
      path: '/musicas'
      fullPath: '/app/musicas'
      preLoaderRoute: typeof AppMusicasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/poemas': {
      id: '/app/poemas'
      path: '/poemas'
      fullPath: '/app/poemas'
      preLoaderRoute: typeof AppPoemasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/conteudos/$conteudoId': {
      id: '/admin/conteudos/$conteudoId'
      path: '/$conteudoId'
      fullPath: '/admin/conteudos/$conteudoId'
      preLoaderRoute: typeof AdminConteudosConteudoIdRouteImport
      parentRoute: typeof AdminConteudosRoute
    }
    '/app/conteudos/$conteudoId': {
      id: '/app/conteudos/$conteudoId'
      path: '/conteudos/$conteudoId'
      fullPath: '/app/conteudos/$conteudoId'
      preLoaderRoute: typeof AppConteudosConteudoIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/perfil/senha': {
      id: '/app/perfil/senha'
      path: '/senha'
      fullPath: '/app/perfil/senha'
      preLoaderRoute: typeof AppPerfilSenhaRouteImport
      parentRoute: typeof AppPerfilRoute
    }
  }
}

interface AdminConteudosRouteChildren {
  AdminConteudosConteudoIdRoute: typeof AdminConteudosConteudoIdRoute
}

const AdminConteudosRouteChildren: AdminConteudosRouteChildren = {
  AdminConteudosConteudoIdRoute: AdminConteudosConteudoIdRoute,
}

const AdminConteudosRouteWithChildren = AdminConteudosRoute._addFileChildren(
  AdminConteudosRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAlunosRoute: typeof AdminAlunosRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminConteudosRoute: typeof AdminConteudosRouteWithChildren
  AdminPerfilRoute: typeof AdminPerfilRoute
  AdminRequerimentosSenhaRoute: typeof AdminRequerimentosSenhaRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAlunosRoute: AdminAlunosRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminConteudosRoute: AdminConteudosRouteWithChildren,
  AdminPerfilRoute: AdminPerfilRoute,
  AdminRequerimentosSenhaRoute: AdminRequerimentosSenhaRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppPerfilRouteChildren {
  AppPerfilSenhaRoute: typeof AppPerfilSenhaRoute
}

const AppPerfilRouteChildren: AppPerfilRouteChildren = {
  AppPerfilSenhaRoute: AppPerfilSenhaRoute,
}

const AppPerfilRouteWithChildren = AppPerfilRoute._addFileChildren(
  AppPerfilRouteChildren,
)

interface AppRouteRouteChildren {
  AppCronicasRoute: typeof AppCronicasRoute
  AppLivrosRoute: typeof AppLivrosRoute
  AppMusicasRoute: typeof AppMusicasRoute
  AppPerfilRoute: typeof AppPerfilRouteWithChildren
  AppPoemasRoute: typeof AppPoemasRoute
  AppIndexRoute: typeof AppIndexRoute
  AppConteudosConteudoIdRoute: typeof AppConteudosConteudoIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCronicasRoute: AppCronicasRoute,
  AppLivrosRoute: AppLivrosRoute,
  AppMusicasRoute: AppMusicasRoute,
  AppPerfilRoute: AppPerfilRouteWithChildren,
  AppPoemasRoute: AppPoemasRoute,
  AppIndexRoute: AppIndexRoute,
  AppConteudosConteudoIdRoute: AppConteudosConteudoIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
